typography_spectrum: 0.777507578022778
color:
  brandStrength: 0.45234502805396914
  lightness: 0.7516187313012779
  saturation: 0.7867327402345836
  rhythmicContrast: 0.9109068873804063
  brandColors:
    - '#FFFFFF'
    - '#F9E27C'
    - '#23241F'
    - '#80531D'
    - '#CD973E'
layout_spectrum: 0.7028733710758388
name: Superhero Pythons
navigation:
  - name: Facebook
    url: 'https://www.facebook.com/SuperheroPythons'
    type: external
title: Superhero Pythons
description: Snakes with superpowers
