layout_spectrum: 0.6643483759835362
typography_spectrum: 0.8777225620578974
color:
  brandStrength: 0.4855711213313043
  lightness: 0.9146311061922461
  saturation: 0.8597491509281099
  rhythmicContrast: 0.3856530962511897
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
name: Superhero Pythons
navigation:
  - name: Facebook
    url: 'https://www.facebook.com/SuperheroPythons'
    type: external
title: Superhero Pythons
description: Snakes with superpowers
